// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: skylr-overseer/skylr-overseer.proto

package pbovr

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// OverseerClient is the client API for Overseer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Overseer - grpc overseer service
type OverseerClient interface {
}

type overseerClient struct {
	cc grpc.ClientConnInterface
}

func NewOverseerClient(cc grpc.ClientConnInterface) OverseerClient {
	return &overseerClient{cc}
}

// OverseerServer is the server API for Overseer service.
// All implementations must embed UnimplementedOverseerServer
// for forward compatibility.
//
// Overseer - grpc overseer service
type OverseerServer interface {
	mustEmbedUnimplementedOverseerServer()
}

// UnimplementedOverseerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverseerServer struct{}

func (UnimplementedOverseerServer) mustEmbedUnimplementedOverseerServer() {}
func (UnimplementedOverseerServer) testEmbeddedByValue()                  {}

// UnsafeOverseerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverseerServer will
// result in compilation errors.
type UnsafeOverseerServer interface {
	mustEmbedUnimplementedOverseerServer()
}

func RegisterOverseerServer(s grpc.ServiceRegistrar, srv OverseerServer) {
	// If the following call panics, it indicates UnimplementedOverseerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Overseer_ServiceDesc, srv)
}

// Overseer_ServiceDesc is the grpc.ServiceDesc for Overseer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Overseer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skylr_overseer.v1.Overseer",
	HandlerType: (*OverseerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "skylr-overseer/skylr-overseer.proto",
}
