// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: skylr-shard.proto

package pbshard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest - get request params
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_skylr_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse - get request response
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_skylr_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// SetRequest - set request params
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_skylr_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// SetResponse - set request response
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_skylr_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_proto_rawDescGZIP(), []int{3}
}

// Entry - storage entry
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Entry_ValueStr
	//	*Entry_ValueInt32
	//	*Entry_ValueInt64
	//	*Entry_ValueFloat
	//	*Entry_ValueDouble
	Value isEntry_Value `protobuf_oneof:"value"`
	// ttl
	// NOTE: ALWAYS nil when returned from Get
	Ttl           *durationpb.Duration `protobuf:"bytes,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_skylr_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_skylr_shard_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() isEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetValueStr() string {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueStr); ok {
			return x.ValueStr
		}
	}
	return ""
}

func (x *Entry) GetValueInt32() int32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt32); ok {
			return x.ValueInt32
		}
	}
	return 0
}

func (x *Entry) GetValueInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt64); ok {
			return x.ValueInt64
		}
	}
	return 0
}

func (x *Entry) GetValueFloat() float32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueFloat); ok {
			return x.ValueFloat
		}
	}
	return 0
}

func (x *Entry) GetValueDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueDouble); ok {
			return x.ValueDouble
		}
	}
	return 0
}

func (x *Entry) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type isEntry_Value interface {
	isEntry_Value()
}

type Entry_ValueStr struct {
	// str value
	ValueStr string `protobuf:"bytes,2,opt,name=value_str,json=valueStr,proto3,oneof"`
}

type Entry_ValueInt32 struct {
	// int32 value
	ValueInt32 int32 `protobuf:"varint,3,opt,name=value_int32,json=valueInt32,proto3,oneof"`
}

type Entry_ValueInt64 struct {
	// int64 value
	ValueInt64 int64 `protobuf:"varint,4,opt,name=value_int64,json=valueInt64,proto3,oneof"`
}

type Entry_ValueFloat struct {
	// float32 value
	ValueFloat float32 `protobuf:"fixed32,5,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Entry_ValueDouble struct {
	// float64 value
	ValueDouble float64 `protobuf:"fixed64,6,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

func (*Entry_ValueStr) isEntry_Value() {}

func (*Entry_ValueInt32) isEntry_Value() {}

func (*Entry_ValueInt64) isEntry_Value() {}

func (*Entry_ValueFloat) isEntry_Value() {}

func (*Entry_ValueDouble) isEntry_Value() {}

var File_skylr_shard_proto protoreflect.FileDescriptor

const file_skylr_shard_proto_rawDesc = "" +
	"\n" +
	"\x11skylr-shard.proto\x12\x0eskylr_shard.v1\x1a\x1egoogle/protobuf/duration.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\vGetResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\"9\n" +
	"\n" +
	"SetRequest\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\"\r\n" +
	"\vSetResponse\"\xfc\x01\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\tvalue_str\x18\x02 \x01(\tH\x00R\bvalueStr\x12!\n" +
	"\vvalue_int32\x18\x03 \x01(\x05H\x00R\n" +
	"valueInt32\x12!\n" +
	"\vvalue_int64\x18\x04 \x01(\x03H\x00R\n" +
	"valueInt64\x12!\n" +
	"\vvalue_float\x18\x05 \x01(\x02H\x00R\n" +
	"valueFloat\x12#\n" +
	"\fvalue_double\x18\x06 \x01(\x01H\x00R\vvalueDouble\x12+\n" +
	"\x03ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\x03ttlB\a\n" +
	"\x05value2\x87\x01\n" +
	"\x05Shard\x12>\n" +
	"\x03Get\x12\x1a.skylr_shard.v1.GetRequest\x1a\x1b.skylr_shard.v1.GetResponse\x12>\n" +
	"\x03Set\x12\x1a.skylr_shard.v1.SetRequest\x1a\x1b.skylr_shard.v1.SetResponseB\x17Z\x15./skylr-shard;pbshardb\x06proto3"

var (
	file_skylr_shard_proto_rawDescOnce sync.Once
	file_skylr_shard_proto_rawDescData []byte
)

func file_skylr_shard_proto_rawDescGZIP() []byte {
	file_skylr_shard_proto_rawDescOnce.Do(func() {
		file_skylr_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skylr_shard_proto_rawDesc), len(file_skylr_shard_proto_rawDesc)))
	})
	return file_skylr_shard_proto_rawDescData
}

var file_skylr_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_skylr_shard_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: skylr_shard.v1.GetRequest
	(*GetResponse)(nil),         // 1: skylr_shard.v1.GetResponse
	(*SetRequest)(nil),          // 2: skylr_shard.v1.SetRequest
	(*SetResponse)(nil),         // 3: skylr_shard.v1.SetResponse
	(*Entry)(nil),               // 4: skylr_shard.v1.Entry
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_skylr_shard_proto_depIdxs = []int32{
	4, // 0: skylr_shard.v1.GetResponse.entry:type_name -> skylr_shard.v1.Entry
	4, // 1: skylr_shard.v1.SetRequest.entry:type_name -> skylr_shard.v1.Entry
	5, // 2: skylr_shard.v1.Entry.ttl:type_name -> google.protobuf.Duration
	0, // 3: skylr_shard.v1.Shard.Get:input_type -> skylr_shard.v1.GetRequest
	2, // 4: skylr_shard.v1.Shard.Set:input_type -> skylr_shard.v1.SetRequest
	1, // 5: skylr_shard.v1.Shard.Get:output_type -> skylr_shard.v1.GetResponse
	3, // 6: skylr_shard.v1.Shard.Set:output_type -> skylr_shard.v1.SetResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_skylr_shard_proto_init() }
func file_skylr_shard_proto_init() {
	if File_skylr_shard_proto != nil {
		return
	}
	file_skylr_shard_proto_msgTypes[4].OneofWrappers = []any{
		(*Entry_ValueStr)(nil),
		(*Entry_ValueInt32)(nil),
		(*Entry_ValueInt64)(nil),
		(*Entry_ValueFloat)(nil),
		(*Entry_ValueDouble)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skylr_shard_proto_rawDesc), len(file_skylr_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skylr_shard_proto_goTypes,
		DependencyIndexes: file_skylr_shard_proto_depIdxs,
		MessageInfos:      file_skylr_shard_proto_msgTypes,
	}.Build()
	File_skylr_shard_proto = out.File
	file_skylr_shard_proto_goTypes = nil
	file_skylr_shard_proto_depIdxs = nil
}
