// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: skylr-overseer/skylr-overseer.proto

package pbovr

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Overseer_Register_FullMethodName    = "/skylr_overseer.v1.Overseer/Register"
	Overseer_Lookup_FullMethodName      = "/skylr_overseer.v1.Overseer/Lookup"
	Overseer_Provision_FullMethodName   = "/skylr_overseer.v1.Overseer/Provision"
	Overseer_Deprovision_FullMethodName = "/skylr_overseer.v1.Overseer/Deprovision"
)

// OverseerClient is the client API for Overseer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Overseer - grpc overseer service
type OverseerClient interface {
	// Register registers a new shard in the system
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Lookup returns the address of the shard responsible for the given key
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// Provision creates a new shard via the provisioner and returns its address when registered.
	Provision(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProvisionResponse, error)
	// Deprovision removes the shard at the given address from the ring and stops it.
	Deprovision(ctx context.Context, in *DeprovisionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type overseerClient struct {
	cc grpc.ClientConnInterface
}

func NewOverseerClient(cc grpc.ClientConnInterface) OverseerClient {
	return &overseerClient{cc}
}

func (c *overseerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Overseer_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overseerClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, Overseer_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overseerClient) Provision(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, Overseer_Provision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overseerClient) Deprovision(ctx context.Context, in *DeprovisionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Overseer_Deprovision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverseerServer is the server API for Overseer service.
// All implementations must embed UnimplementedOverseerServer
// for forward compatibility.
//
// Overseer - grpc overseer service
type OverseerServer interface {
	// Register registers a new shard in the system
	Register(context.Context, *RegisterRequest) (*empty.Empty, error)
	// Lookup returns the address of the shard responsible for the given key
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	// Provision creates a new shard via the provisioner and returns its address when registered.
	Provision(context.Context, *empty.Empty) (*ProvisionResponse, error)
	// Deprovision removes the shard at the given address from the ring and stops it.
	Deprovision(context.Context, *DeprovisionRequest) (*empty.Empty, error)
	mustEmbedUnimplementedOverseerServer()
}

// UnimplementedOverseerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverseerServer struct{}

func (UnimplementedOverseerServer) Register(context.Context, *RegisterRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedOverseerServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedOverseerServer) Provision(context.Context, *empty.Empty) (*ProvisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedOverseerServer) Deprovision(context.Context, *DeprovisionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deprovision not implemented")
}
func (UnimplementedOverseerServer) mustEmbedUnimplementedOverseerServer() {}
func (UnimplementedOverseerServer) testEmbeddedByValue()                  {}

// UnsafeOverseerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverseerServer will
// result in compilation errors.
type UnsafeOverseerServer interface {
	mustEmbedUnimplementedOverseerServer()
}

func RegisterOverseerServer(s grpc.ServiceRegistrar, srv OverseerServer) {
	// If the following call pancis, it indicates UnimplementedOverseerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Overseer_ServiceDesc, srv)
}

func _Overseer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverseerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Overseer_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverseerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overseer_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverseerServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Overseer_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverseerServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overseer_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverseerServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Overseer_Provision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverseerServer).Provision(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overseer_Deprovision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeprovisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverseerServer).Deprovision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Overseer_Deprovision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverseerServer).Deprovision(ctx, req.(*DeprovisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Overseer_ServiceDesc is the grpc.ServiceDesc for Overseer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Overseer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skylr_overseer.v1.Overseer",
	HandlerType: (*OverseerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Overseer_Register_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Overseer_Lookup_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _Overseer_Provision_Handler,
		},
		{
			MethodName: "Deprovision",
			Handler:    _Overseer_Deprovision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skylr-overseer/skylr-overseer.proto",
}
