// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: skylr-shard/skylr-shard.proto

package pbshard

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest - get request params
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse - get request response
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// SetRequest - set request params
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *InputEntry            `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetInput() *InputEntry {
	if x != nil {
		return x.Input
	}
	return nil
}

// SetResponse - set request response
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{3}
}

// Entry - storage entry
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Entry_ValueStr
	//	*Entry_ValueInt32
	//	*Entry_ValueInt64
	//	*Entry_ValueFloat
	//	*Entry_ValueDouble
	Value         isEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() isEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetValueStr() string {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueStr); ok {
			return x.ValueStr
		}
	}
	return ""
}

func (x *Entry) GetValueInt32() int32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt32); ok {
			return x.ValueInt32
		}
	}
	return 0
}

func (x *Entry) GetValueInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt64); ok {
			return x.ValueInt64
		}
	}
	return 0
}

func (x *Entry) GetValueFloat() float32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueFloat); ok {
			return x.ValueFloat
		}
	}
	return 0
}

func (x *Entry) GetValueDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueDouble); ok {
			return x.ValueDouble
		}
	}
	return 0
}

type isEntry_Value interface {
	isEntry_Value()
}

type Entry_ValueStr struct {
	// str value
	ValueStr string `protobuf:"bytes,2,opt,name=value_str,json=valueStr,proto3,oneof"`
}

type Entry_ValueInt32 struct {
	// int32 value
	ValueInt32 int32 `protobuf:"varint,3,opt,name=value_int32,json=valueInt32,proto3,oneof"`
}

type Entry_ValueInt64 struct {
	// int64 value
	ValueInt64 int64 `protobuf:"varint,4,opt,name=value_int64,json=valueInt64,proto3,oneof"`
}

type Entry_ValueFloat struct {
	// float32 value
	ValueFloat float32 `protobuf:"fixed32,5,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Entry_ValueDouble struct {
	// float64 value
	ValueDouble float64 `protobuf:"fixed64,6,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

func (*Entry_ValueStr) isEntry_Value() {}

func (*Entry_ValueInt32) isEntry_Value() {}

func (*Entry_ValueInt64) isEntry_Value() {}

func (*Entry_ValueFloat) isEntry_Value() {}

func (*Entry_ValueDouble) isEntry_Value() {}

// InputEntry - input storage entry
type InputEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// ttl
	Ttl           *durationpb.Duration `protobuf:"bytes,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEntry) Reset() {
	*x = InputEntry{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEntry) ProtoMessage() {}

func (x *InputEntry) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEntry.ProtoReflect.Descriptor instead.
func (*InputEntry) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{5}
}

func (x *InputEntry) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *InputEntry) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumElements   int64                  `protobuf:"varint,1,opt,name=num_elements,json=numElements,proto3" json:"num_elements,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsResponse) GetNumElements() int64 {
	if x != nil {
		return x.NumElements
	}
	return 0
}

func (x *MetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

var File_skylr_shard_skylr_shard_proto protoreflect.FileDescriptor

const file_skylr_shard_skylr_shard_proto_rawDesc = "" +
	"\n" +
	"\x1dskylr-shard/skylr-shard.proto\x12\x0eskylr_shard.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\vGetResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\">\n" +
	"\n" +
	"SetRequest\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.skylr_shard.v1.InputEntryR\x05input\"\r\n" +
	"\vSetResponse\"\xcf\x01\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\tvalue_str\x18\x02 \x01(\tH\x00R\bvalueStr\x12!\n" +
	"\vvalue_int32\x18\x03 \x01(\x05H\x00R\n" +
	"valueInt32\x12!\n" +
	"\vvalue_int64\x18\x04 \x01(\x03H\x00R\n" +
	"valueInt64\x12!\n" +
	"\vvalue_float\x18\x05 \x01(\x02H\x00R\n" +
	"valueFloat\x12#\n" +
	"\fvalue_double\x18\x06 \x01(\x01H\x00R\vvalueDoubleB\a\n" +
	"\x05value\"f\n" +
	"\n" +
	"InputEntry\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\x12+\n" +
	"\x03ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"Q\n" +
	"\x0fMetricsResponse\x12!\n" +
	"\fnum_elements\x18\x01 \x01(\x03R\vnumElements\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage2\x8e\x02\n" +
	"\x05Shard\x12S\n" +
	"\x03Get\x12\x1a.skylr_shard.v1.GetRequest\x1a\x1b.skylr_shard.v1.GetResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/v1/get\x12Q\n" +
	"\x03Set\x12\x1a.skylr_shard.v1.SetRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/set\x12]\n" +
	"\aMetrics\x12\x16.google.protobuf.Empty\x1a\x1f.skylr_shard.v1.MetricsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/metrics0\x01B\x17Z\x15./skylr-shard;pbshardb\x06proto3"

var (
	file_skylr_shard_skylr_shard_proto_rawDescOnce sync.Once
	file_skylr_shard_skylr_shard_proto_rawDescData []byte
)

func file_skylr_shard_skylr_shard_proto_rawDescGZIP() []byte {
	file_skylr_shard_skylr_shard_proto_rawDescOnce.Do(func() {
		file_skylr_shard_skylr_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skylr_shard_skylr_shard_proto_rawDesc), len(file_skylr_shard_skylr_shard_proto_rawDesc)))
	})
	return file_skylr_shard_skylr_shard_proto_rawDescData
}

var file_skylr_shard_skylr_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_skylr_shard_skylr_shard_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: skylr_shard.v1.GetRequest
	(*GetResponse)(nil),         // 1: skylr_shard.v1.GetResponse
	(*SetRequest)(nil),          // 2: skylr_shard.v1.SetRequest
	(*SetResponse)(nil),         // 3: skylr_shard.v1.SetResponse
	(*Entry)(nil),               // 4: skylr_shard.v1.Entry
	(*InputEntry)(nil),          // 5: skylr_shard.v1.InputEntry
	(*MetricsResponse)(nil),     // 6: skylr_shard.v1.MetricsResponse
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_skylr_shard_skylr_shard_proto_depIdxs = []int32{
	4, // 0: skylr_shard.v1.GetResponse.entry:type_name -> skylr_shard.v1.Entry
	5, // 1: skylr_shard.v1.SetRequest.input:type_name -> skylr_shard.v1.InputEntry
	4, // 2: skylr_shard.v1.InputEntry.entry:type_name -> skylr_shard.v1.Entry
	7, // 3: skylr_shard.v1.InputEntry.ttl:type_name -> google.protobuf.Duration
	0, // 4: skylr_shard.v1.Shard.Get:input_type -> skylr_shard.v1.GetRequest
	2, // 5: skylr_shard.v1.Shard.Set:input_type -> skylr_shard.v1.SetRequest
	8, // 6: skylr_shard.v1.Shard.Metrics:input_type -> google.protobuf.Empty
	1, // 7: skylr_shard.v1.Shard.Get:output_type -> skylr_shard.v1.GetResponse
	8, // 8: skylr_shard.v1.Shard.Set:output_type -> google.protobuf.Empty
	6, // 9: skylr_shard.v1.Shard.Metrics:output_type -> skylr_shard.v1.MetricsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_skylr_shard_skylr_shard_proto_init() }
func file_skylr_shard_skylr_shard_proto_init() {
	if File_skylr_shard_skylr_shard_proto != nil {
		return
	}
	file_skylr_shard_skylr_shard_proto_msgTypes[4].OneofWrappers = []any{
		(*Entry_ValueStr)(nil),
		(*Entry_ValueInt32)(nil),
		(*Entry_ValueInt64)(nil),
		(*Entry_ValueFloat)(nil),
		(*Entry_ValueDouble)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skylr_shard_skylr_shard_proto_rawDesc), len(file_skylr_shard_skylr_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skylr_shard_skylr_shard_proto_goTypes,
		DependencyIndexes: file_skylr_shard_skylr_shard_proto_depIdxs,
		MessageInfos:      file_skylr_shard_skylr_shard_proto_msgTypes,
	}.Build()
	File_skylr_shard_skylr_shard_proto = out.File
	file_skylr_shard_skylr_shard_proto_goTypes = nil
	file_skylr_shard_skylr_shard_proto_depIdxs = nil
}
