// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: skylr-shard/skylr-shard.proto

package pbshard

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest - get request params
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse - get request response
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// SetRequest - set request params
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *InputEntry            `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetInput() *InputEntry {
	if x != nil {
		return x.Input
	}
	return nil
}

// SetResponse - set request response
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{3}
}

// DeleteRequest - delete request params
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse - delete response
type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deleted indicates whether the key existed and was deleted
	// true - key existed and was deleted
	// false - key did not exist (no-op)
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Entry - storage entry
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Entry_ValueStr
	//	*Entry_ValueInt32
	//	*Entry_ValueInt64
	//	*Entry_ValueFloat
	//	*Entry_ValueDouble
	Value         isEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{6}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() isEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetValueStr() string {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueStr); ok {
			return x.ValueStr
		}
	}
	return ""
}

func (x *Entry) GetValueInt32() int32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt32); ok {
			return x.ValueInt32
		}
	}
	return 0
}

func (x *Entry) GetValueInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueInt64); ok {
			return x.ValueInt64
		}
	}
	return 0
}

func (x *Entry) GetValueFloat() float32 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueFloat); ok {
			return x.ValueFloat
		}
	}
	return 0
}

func (x *Entry) GetValueDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Entry_ValueDouble); ok {
			return x.ValueDouble
		}
	}
	return 0
}

type isEntry_Value interface {
	isEntry_Value()
}

type Entry_ValueStr struct {
	// str value
	ValueStr string `protobuf:"bytes,2,opt,name=value_str,json=valueStr,proto3,oneof"`
}

type Entry_ValueInt32 struct {
	// int32 value
	ValueInt32 int32 `protobuf:"varint,3,opt,name=value_int32,json=valueInt32,proto3,oneof"`
}

type Entry_ValueInt64 struct {
	// int64 value
	ValueInt64 int64 `protobuf:"varint,4,opt,name=value_int64,json=valueInt64,proto3,oneof"`
}

type Entry_ValueFloat struct {
	// float32 value
	ValueFloat float32 `protobuf:"fixed32,5,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Entry_ValueDouble struct {
	// float64 value
	ValueDouble float64 `protobuf:"fixed64,6,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

func (*Entry_ValueStr) isEntry_Value() {}

func (*Entry_ValueInt32) isEntry_Value() {}

func (*Entry_ValueInt64) isEntry_Value() {}

func (*Entry_ValueFloat) isEntry_Value() {}

func (*Entry_ValueDouble) isEntry_Value() {}

// InputEntry - input storage entry
type InputEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// ttl
	Ttl           *duration.Duration `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEntry) Reset() {
	*x = InputEntry{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEntry) ProtoMessage() {}

func (x *InputEntry) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEntry.ProtoReflect.Descriptor instead.
func (*InputEntry) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{7}
}

func (x *InputEntry) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *InputEntry) GetTtl() *duration.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// ScanResponse - a single entry streamed during Scan
type ScanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry is the stored key-value pair
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// remaining_ttl is the remaining time-to-live for this entry
	RemainingTtl  *duration.Duration `protobuf:"bytes,2,opt,name=remaining_ttl,json=remainingTtl,proto3" json:"remaining_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{8}
}

func (x *ScanResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ScanResponse) GetRemainingTtl() *duration.Duration {
	if x != nil {
		return x.RemainingTtl
	}
	return nil
}

// MetricsResponse - service metrics snapshot
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// system
	CpuUsage             float64 `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryRssBytes       uint64  `protobuf:"varint,2,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`                     // process RSS (what OS/OOM killer sees)
	MemoryHeapAllocBytes uint64  `protobuf:"varint,3,opt,name=memory_heap_alloc_bytes,json=memoryHeapAllocBytes,proto3" json:"memory_heap_alloc_bytes,omitempty"` // Go heap live objects (diagnostics)
	// throughput (cumulative counters, Overseer computes rates)
	TotalGets    uint64 `protobuf:"varint,4,opt,name=total_gets,json=totalGets,proto3" json:"total_gets,omitempty"`
	TotalSets    uint64 `protobuf:"varint,5,opt,name=total_sets,json=totalSets,proto3" json:"total_sets,omitempty"`
	TotalDeletes uint64 `protobuf:"varint,6,opt,name=total_deletes,json=totalDeletes,proto3" json:"total_deletes,omitempty"`
	// uptime
	UptimeSeconds int64 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_shard_skylr_shard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_skylr_shard_skylr_shard_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsResponse) GetMemoryRssBytes() uint64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *MetricsResponse) GetMemoryHeapAllocBytes() uint64 {
	if x != nil {
		return x.MemoryHeapAllocBytes
	}
	return 0
}

func (x *MetricsResponse) GetTotalGets() uint64 {
	if x != nil {
		return x.TotalGets
	}
	return 0
}

func (x *MetricsResponse) GetTotalSets() uint64 {
	if x != nil {
		return x.TotalSets
	}
	return 0
}

func (x *MetricsResponse) GetTotalDeletes() uint64 {
	if x != nil {
		return x.TotalDeletes
	}
	return 0
}

func (x *MetricsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_skylr_shard_skylr_shard_proto protoreflect.FileDescriptor

const file_skylr_shard_skylr_shard_proto_rawDesc = "" +
	"\n" +
	"\x1dskylr-shard/skylr-shard.proto\x12\x0eskylr_shard.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\vGetResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\">\n" +
	"\n" +
	"SetRequest\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.skylr_shard.v1.InputEntryR\x05input\"\r\n" +
	"\vSetResponse\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xcf\x01\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\tvalue_str\x18\x02 \x01(\tH\x00R\bvalueStr\x12!\n" +
	"\vvalue_int32\x18\x03 \x01(\x05H\x00R\n" +
	"valueInt32\x12!\n" +
	"\vvalue_int64\x18\x04 \x01(\x03H\x00R\n" +
	"valueInt64\x12!\n" +
	"\vvalue_float\x18\x05 \x01(\x02H\x00R\n" +
	"valueFloat\x12#\n" +
	"\fvalue_double\x18\x06 \x01(\x01H\x00R\vvalueDoubleB\a\n" +
	"\x05value\"f\n" +
	"\n" +
	"InputEntry\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"{\n" +
	"\fScanResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.skylr_shard.v1.EntryR\x05entry\x12>\n" +
	"\rremaining_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\fremainingTtl\"\x99\x02\n" +
	"\x0fMetricsResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12(\n" +
	"\x10memory_rss_bytes\x18\x02 \x01(\x04R\x0ememoryRssBytes\x125\n" +
	"\x17memory_heap_alloc_bytes\x18\x03 \x01(\x04R\x14memoryHeapAllocBytes\x12\x1d\n" +
	"\n" +
	"total_gets\x18\x04 \x01(\x04R\ttotalGets\x12\x1d\n" +
	"\n" +
	"total_sets\x18\x05 \x01(\x04R\ttotalSets\x12#\n" +
	"\rtotal_deletes\x18\x06 \x01(\x04R\ftotalDeletes\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds2\xad\x03\n" +
	"\x05Shard\x12S\n" +
	"\x03Get\x12\x1a.skylr_shard.v1.GetRequest\x1a\x1b.skylr_shard.v1.GetResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/v1/get\x12Q\n" +
	"\x03Set\x12\x1a.skylr_shard.v1.SetRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/set\x12_\n" +
	"\x06Delete\x12\x1d.skylr_shard.v1.DeleteRequest\x1a\x1e.skylr_shard.v1.DeleteResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/v1/delete\x12[\n" +
	"\aMetrics\x12\x16.google.protobuf.Empty\x1a\x1f.skylr_shard.v1.MetricsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/metrics\x12>\n" +
	"\x04Scan\x12\x16.google.protobuf.Empty\x1a\x1c.skylr_shard.v1.ScanResponse0\x01B\x17Z\x15./skylr-shard;pbshardb\x06proto3"

var (
	file_skylr_shard_skylr_shard_proto_rawDescOnce sync.Once
	file_skylr_shard_skylr_shard_proto_rawDescData []byte
)

func file_skylr_shard_skylr_shard_proto_rawDescGZIP() []byte {
	file_skylr_shard_skylr_shard_proto_rawDescOnce.Do(func() {
		file_skylr_shard_skylr_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skylr_shard_skylr_shard_proto_rawDesc), len(file_skylr_shard_skylr_shard_proto_rawDesc)))
	})
	return file_skylr_shard_skylr_shard_proto_rawDescData
}

var file_skylr_shard_skylr_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_skylr_shard_skylr_shard_proto_goTypes = []any{
	(*GetRequest)(nil),        // 0: skylr_shard.v1.GetRequest
	(*GetResponse)(nil),       // 1: skylr_shard.v1.GetResponse
	(*SetRequest)(nil),        // 2: skylr_shard.v1.SetRequest
	(*SetResponse)(nil),       // 3: skylr_shard.v1.SetResponse
	(*DeleteRequest)(nil),     // 4: skylr_shard.v1.DeleteRequest
	(*DeleteResponse)(nil),    // 5: skylr_shard.v1.DeleteResponse
	(*Entry)(nil),             // 6: skylr_shard.v1.Entry
	(*InputEntry)(nil),        // 7: skylr_shard.v1.InputEntry
	(*ScanResponse)(nil),      // 8: skylr_shard.v1.ScanResponse
	(*MetricsResponse)(nil),   // 9: skylr_shard.v1.MetricsResponse
	(*duration.Duration)(nil), // 10: google.protobuf.Duration
	(*empty.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_skylr_shard_skylr_shard_proto_depIdxs = []int32{
	6,  // 0: skylr_shard.v1.GetResponse.entry:type_name -> skylr_shard.v1.Entry
	7,  // 1: skylr_shard.v1.SetRequest.input:type_name -> skylr_shard.v1.InputEntry
	6,  // 2: skylr_shard.v1.InputEntry.entry:type_name -> skylr_shard.v1.Entry
	10, // 3: skylr_shard.v1.InputEntry.ttl:type_name -> google.protobuf.Duration
	6,  // 4: skylr_shard.v1.ScanResponse.entry:type_name -> skylr_shard.v1.Entry
	10, // 5: skylr_shard.v1.ScanResponse.remaining_ttl:type_name -> google.protobuf.Duration
	0,  // 6: skylr_shard.v1.Shard.Get:input_type -> skylr_shard.v1.GetRequest
	2,  // 7: skylr_shard.v1.Shard.Set:input_type -> skylr_shard.v1.SetRequest
	4,  // 8: skylr_shard.v1.Shard.Delete:input_type -> skylr_shard.v1.DeleteRequest
	11, // 9: skylr_shard.v1.Shard.Metrics:input_type -> google.protobuf.Empty
	11, // 10: skylr_shard.v1.Shard.Scan:input_type -> google.protobuf.Empty
	1,  // 11: skylr_shard.v1.Shard.Get:output_type -> skylr_shard.v1.GetResponse
	11, // 12: skylr_shard.v1.Shard.Set:output_type -> google.protobuf.Empty
	5,  // 13: skylr_shard.v1.Shard.Delete:output_type -> skylr_shard.v1.DeleteResponse
	9,  // 14: skylr_shard.v1.Shard.Metrics:output_type -> skylr_shard.v1.MetricsResponse
	8,  // 15: skylr_shard.v1.Shard.Scan:output_type -> skylr_shard.v1.ScanResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_skylr_shard_skylr_shard_proto_init() }
func file_skylr_shard_skylr_shard_proto_init() {
	if File_skylr_shard_skylr_shard_proto != nil {
		return
	}
	file_skylr_shard_skylr_shard_proto_msgTypes[6].OneofWrappers = []any{
		(*Entry_ValueStr)(nil),
		(*Entry_ValueInt32)(nil),
		(*Entry_ValueInt64)(nil),
		(*Entry_ValueFloat)(nil),
		(*Entry_ValueDouble)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skylr_shard_skylr_shard_proto_rawDesc), len(file_skylr_shard_skylr_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skylr_shard_skylr_shard_proto_goTypes,
		DependencyIndexes: file_skylr_shard_skylr_shard_proto_depIdxs,
		MessageInfos:      file_skylr_shard_skylr_shard_proto_msgTypes,
	}.Build()
	File_skylr_shard_skylr_shard_proto = out.File
	file_skylr_shard_skylr_shard_proto_goTypes = nil
	file_skylr_shard_skylr_shard_proto_depIdxs = nil
}
