// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

import (
	context "context"
	"errors"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	empty "github.com/golang/protobuf/ptypes/empty"
	mm_pbshard "github.com/r-heap47/skylr/skylr-overseer/internal/pb/skylr-shard"
	grpc "google.golang.org/grpc"
)

// ShardClientMock implements mm_pbshard.ShardClient
type ShardClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDelete          func(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption) (dp1 *mm_pbshard.DeleteResponse, err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mShardClientMockDelete

	funcGet          func(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption) (gp1 *mm_pbshard.GetResponse, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mShardClientMockGet

	funcMetrics          func(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (mp1 *mm_pbshard.MetricsResponse, err error)
	funcMetricsOrigin    string
	inspectFuncMetrics   func(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption)
	afterMetricsCounter  uint64
	beforeMetricsCounter uint64
	MetricsMock          mShardClientMockMetrics

	funcSet          func(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption) (ep1 *empty.Empty, err error)
	funcSetOrigin    string
	inspectFuncSet   func(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption)
	afterSetCounter  uint64
	beforeSetCounter uint64
	SetMock          mShardClientMockSet
}

// Scan is a minimal stub that satisfies the mm_pbshard.ShardClient interface.
// Observer tests do not exercise Scan; actual Scan usage is tested via integration tests.
func (m *ShardClientMock) Scan(_ context.Context, _ *empty.Empty, _ ...grpc.CallOption) (grpc.ServerStreamingClient[mm_pbshard.ScanResponse], error) {
	return nil, errors.New("Scan: not implemented in mock")
}

// NewShardClientMock returns a mock for mm_pbshard.ShardClient
func NewShardClientMock(t minimock.Tester) *ShardClientMock {
	m := &ShardClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteMock = mShardClientMockDelete{mock: m}
	m.DeleteMock.callArgs = []*ShardClientMockDeleteParams{}

	m.GetMock = mShardClientMockGet{mock: m}
	m.GetMock.callArgs = []*ShardClientMockGetParams{}

	m.MetricsMock = mShardClientMockMetrics{mock: m}
	m.MetricsMock.callArgs = []*ShardClientMockMetricsParams{}

	m.SetMock = mShardClientMockSet{mock: m}
	m.SetMock.callArgs = []*ShardClientMockSetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mShardClientMockDelete struct {
	optional           bool
	mock               *ShardClientMock
	defaultExpectation *ShardClientMockDeleteExpectation
	expectations       []*ShardClientMockDeleteExpectation

	callArgs []*ShardClientMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShardClientMockDeleteExpectation specifies expectation struct of the ShardClient.Delete
type ShardClientMockDeleteExpectation struct {
	mock               *ShardClientMock
	params             *ShardClientMockDeleteParams
	paramPtrs          *ShardClientMockDeleteParamPtrs
	expectationOrigins ShardClientMockDeleteExpectationOrigins
	results            *ShardClientMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// ShardClientMockDeleteParams contains parameters of the ShardClient.Delete
type ShardClientMockDeleteParams struct {
	ctx  context.Context
	in   *mm_pbshard.DeleteRequest
	opts []grpc.CallOption
}

// ShardClientMockDeleteParamPtrs contains pointers to parameters of the ShardClient.Delete
type ShardClientMockDeleteParamPtrs struct {
	ctx  *context.Context
	in   **mm_pbshard.DeleteRequest
	opts *[]grpc.CallOption
}

// ShardClientMockDeleteResults contains results of the ShardClient.Delete
type ShardClientMockDeleteResults struct {
	dp1 *mm_pbshard.DeleteResponse
	err error
}

// ShardClientMockDeleteOrigins contains origins of expectations of the ShardClient.Delete
type ShardClientMockDeleteExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mShardClientMockDelete) Optional() *mShardClientMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for ShardClient.Delete
func (mmDelete *mShardClientMockDelete) Expect(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption) *mShardClientMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ShardClientMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &ShardClientMockDeleteParams{ctx, in, opts}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for ShardClient.Delete
func (mmDelete *mShardClientMockDelete) ExpectCtxParam1(ctx context.Context) *mShardClientMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ShardClientMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &ShardClientMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectInParam2 sets up expected param in for ShardClient.Delete
func (mmDelete *mShardClientMockDelete) ExpectInParam2(in *mm_pbshard.DeleteRequest) *mShardClientMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ShardClientMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &ShardClientMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.in = &in
	mmDelete.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectOptsParam3 sets up expected param opts for ShardClient.Delete
func (mmDelete *mShardClientMockDelete) ExpectOptsParam3(opts ...grpc.CallOption) *mShardClientMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ShardClientMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &ShardClientMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.opts = &opts
	mmDelete.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the ShardClient.Delete
func (mmDelete *mShardClientMockDelete) Inspect(f func(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption)) *mShardClientMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for ShardClientMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by ShardClient.Delete
func (mmDelete *mShardClientMockDelete) Return(dp1 *mm_pbshard.DeleteResponse, err error) *ShardClientMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &ShardClientMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &ShardClientMockDeleteResults{dp1, err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the ShardClient.Delete method
func (mmDelete *mShardClientMockDelete) Set(f func(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption) (dp1 *mm_pbshard.DeleteResponse, err error)) *ShardClientMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the ShardClient.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the ShardClient.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the ShardClient.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mShardClientMockDelete) When(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption) *ShardClientMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("ShardClientMock.Delete mock is already set by Set")
	}

	expectation := &ShardClientMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &ShardClientMockDeleteParams{ctx, in, opts},
		expectationOrigins: ShardClientMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up ShardClient.Delete return parameters for the expectation previously defined by the When method
func (e *ShardClientMockDeleteExpectation) Then(dp1 *mm_pbshard.DeleteResponse, err error) *ShardClientMock {
	e.results = &ShardClientMockDeleteResults{dp1, err}
	return e.mock
}

// Times sets number of times ShardClient.Delete should be invoked
func (mmDelete *mShardClientMockDelete) Times(n uint64) *mShardClientMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of ShardClientMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mShardClientMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_pbshard.ShardClient
func (mmDelete *ShardClientMock) Delete(ctx context.Context, in *mm_pbshard.DeleteRequest, opts ...grpc.CallOption) (dp1 *mm_pbshard.DeleteResponse, err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, in, opts...)
	}

	mm_params := ShardClientMockDeleteParams{ctx, in, opts}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.dp1, e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := ShardClientMockDeleteParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("ShardClientMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmDelete.t.Errorf("ShardClientMock.Delete got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmDelete.t.Errorf("ShardClientMock.Delete got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("ShardClientMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the ShardClientMock.Delete")
		}
		return (*mm_results).dp1, (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, in, opts...)
	}
	mmDelete.t.Fatalf("Unexpected call to ShardClientMock.Delete. %v %v %v", ctx, in, opts)
	return
}

// DeleteAfterCounter returns a count of finished ShardClientMock.Delete invocations
func (mmDelete *ShardClientMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of ShardClientMock.Delete invocations
func (mmDelete *ShardClientMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to ShardClientMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mShardClientMockDelete) Calls() []*ShardClientMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*ShardClientMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *ShardClientMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *ShardClientMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShardClientMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShardClientMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShardClientMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to ShardClientMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to ShardClientMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mShardClientMockGet struct {
	optional           bool
	mock               *ShardClientMock
	defaultExpectation *ShardClientMockGetExpectation
	expectations       []*ShardClientMockGetExpectation

	callArgs []*ShardClientMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShardClientMockGetExpectation specifies expectation struct of the ShardClient.Get
type ShardClientMockGetExpectation struct {
	mock               *ShardClientMock
	params             *ShardClientMockGetParams
	paramPtrs          *ShardClientMockGetParamPtrs
	expectationOrigins ShardClientMockGetExpectationOrigins
	results            *ShardClientMockGetResults
	returnOrigin       string
	Counter            uint64
}

// ShardClientMockGetParams contains parameters of the ShardClient.Get
type ShardClientMockGetParams struct {
	ctx  context.Context
	in   *mm_pbshard.GetRequest
	opts []grpc.CallOption
}

// ShardClientMockGetParamPtrs contains pointers to parameters of the ShardClient.Get
type ShardClientMockGetParamPtrs struct {
	ctx  *context.Context
	in   **mm_pbshard.GetRequest
	opts *[]grpc.CallOption
}

// ShardClientMockGetResults contains results of the ShardClient.Get
type ShardClientMockGetResults struct {
	gp1 *mm_pbshard.GetResponse
	err error
}

// ShardClientMockGetOrigins contains origins of expectations of the ShardClient.Get
type ShardClientMockGetExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mShardClientMockGet) Optional() *mShardClientMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for ShardClient.Get
func (mmGet *mShardClientMockGet) Expect(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption) *mShardClientMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &ShardClientMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &ShardClientMockGetParams{ctx, in, opts}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for ShardClient.Get
func (mmGet *mShardClientMockGet) ExpectCtxParam1(ctx context.Context) *mShardClientMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &ShardClientMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &ShardClientMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectInParam2 sets up expected param in for ShardClient.Get
func (mmGet *mShardClientMockGet) ExpectInParam2(in *mm_pbshard.GetRequest) *mShardClientMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &ShardClientMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &ShardClientMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.in = &in
	mmGet.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmGet
}

// ExpectOptsParam3 sets up expected param opts for ShardClient.Get
func (mmGet *mShardClientMockGet) ExpectOptsParam3(opts ...grpc.CallOption) *mShardClientMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &ShardClientMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &ShardClientMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.opts = &opts
	mmGet.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the ShardClient.Get
func (mmGet *mShardClientMockGet) Inspect(f func(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption)) *mShardClientMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for ShardClientMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by ShardClient.Get
func (mmGet *mShardClientMockGet) Return(gp1 *mm_pbshard.GetResponse, err error) *ShardClientMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &ShardClientMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &ShardClientMockGetResults{gp1, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the ShardClient.Get method
func (mmGet *mShardClientMockGet) Set(f func(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption) (gp1 *mm_pbshard.GetResponse, err error)) *ShardClientMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the ShardClient.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the ShardClient.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the ShardClient.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mShardClientMockGet) When(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption) *ShardClientMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("ShardClientMock.Get mock is already set by Set")
	}

	expectation := &ShardClientMockGetExpectation{
		mock:               mmGet.mock,
		params:             &ShardClientMockGetParams{ctx, in, opts},
		expectationOrigins: ShardClientMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up ShardClient.Get return parameters for the expectation previously defined by the When method
func (e *ShardClientMockGetExpectation) Then(gp1 *mm_pbshard.GetResponse, err error) *ShardClientMock {
	e.results = &ShardClientMockGetResults{gp1, err}
	return e.mock
}

// Times sets number of times ShardClient.Get should be invoked
func (mmGet *mShardClientMockGet) Times(n uint64) *mShardClientMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of ShardClientMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mShardClientMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_pbshard.ShardClient
func (mmGet *ShardClientMock) Get(ctx context.Context, in *mm_pbshard.GetRequest, opts ...grpc.CallOption) (gp1 *mm_pbshard.GetResponse, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, in, opts...)
	}

	mm_params := ShardClientMockGetParams{ctx, in, opts}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gp1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := ShardClientMockGetParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("ShardClientMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmGet.t.Errorf("ShardClientMock.Get got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmGet.t.Errorf("ShardClientMock.Get got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("ShardClientMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the ShardClientMock.Get")
		}
		return (*mm_results).gp1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, in, opts...)
	}
	mmGet.t.Fatalf("Unexpected call to ShardClientMock.Get. %v %v %v", ctx, in, opts)
	return
}

// GetAfterCounter returns a count of finished ShardClientMock.Get invocations
func (mmGet *ShardClientMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of ShardClientMock.Get invocations
func (mmGet *ShardClientMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to ShardClientMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mShardClientMockGet) Calls() []*ShardClientMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*ShardClientMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *ShardClientMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *ShardClientMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShardClientMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShardClientMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShardClientMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to ShardClientMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to ShardClientMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mShardClientMockMetrics struct {
	optional           bool
	mock               *ShardClientMock
	defaultExpectation *ShardClientMockMetricsExpectation
	expectations       []*ShardClientMockMetricsExpectation

	callArgs []*ShardClientMockMetricsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShardClientMockMetricsExpectation specifies expectation struct of the ShardClient.Metrics
type ShardClientMockMetricsExpectation struct {
	mock               *ShardClientMock
	params             *ShardClientMockMetricsParams
	paramPtrs          *ShardClientMockMetricsParamPtrs
	expectationOrigins ShardClientMockMetricsExpectationOrigins
	results            *ShardClientMockMetricsResults
	returnOrigin       string
	Counter            uint64
}

// ShardClientMockMetricsParams contains parameters of the ShardClient.Metrics
type ShardClientMockMetricsParams struct {
	ctx  context.Context
	in   *empty.Empty
	opts []grpc.CallOption
}

// ShardClientMockMetricsParamPtrs contains pointers to parameters of the ShardClient.Metrics
type ShardClientMockMetricsParamPtrs struct {
	ctx  *context.Context
	in   **empty.Empty
	opts *[]grpc.CallOption
}

// ShardClientMockMetricsResults contains results of the ShardClient.Metrics
type ShardClientMockMetricsResults struct {
	mp1 *mm_pbshard.MetricsResponse
	err error
}

// ShardClientMockMetricsOrigins contains origins of expectations of the ShardClient.Metrics
type ShardClientMockMetricsExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmMetrics *mShardClientMockMetrics) Optional() *mShardClientMockMetrics {
	mmMetrics.optional = true
	return mmMetrics
}

// Expect sets up expected params for ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) Expect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) *mShardClientMockMetrics {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	if mmMetrics.defaultExpectation == nil {
		mmMetrics.defaultExpectation = &ShardClientMockMetricsExpectation{}
	}

	if mmMetrics.defaultExpectation.paramPtrs != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by ExpectParams functions")
	}

	mmMetrics.defaultExpectation.params = &ShardClientMockMetricsParams{ctx, in, opts}
	mmMetrics.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmMetrics.expectations {
		if minimock.Equal(e.params, mmMetrics.defaultExpectation.params) {
			mmMetrics.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmMetrics.defaultExpectation.params)
		}
	}

	return mmMetrics
}

// ExpectCtxParam1 sets up expected param ctx for ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) ExpectCtxParam1(ctx context.Context) *mShardClientMockMetrics {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	if mmMetrics.defaultExpectation == nil {
		mmMetrics.defaultExpectation = &ShardClientMockMetricsExpectation{}
	}

	if mmMetrics.defaultExpectation.params != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Expect")
	}

	if mmMetrics.defaultExpectation.paramPtrs == nil {
		mmMetrics.defaultExpectation.paramPtrs = &ShardClientMockMetricsParamPtrs{}
	}
	mmMetrics.defaultExpectation.paramPtrs.ctx = &ctx
	mmMetrics.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmMetrics
}

// ExpectInParam2 sets up expected param in for ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) ExpectInParam2(in *empty.Empty) *mShardClientMockMetrics {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	if mmMetrics.defaultExpectation == nil {
		mmMetrics.defaultExpectation = &ShardClientMockMetricsExpectation{}
	}

	if mmMetrics.defaultExpectation.params != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Expect")
	}

	if mmMetrics.defaultExpectation.paramPtrs == nil {
		mmMetrics.defaultExpectation.paramPtrs = &ShardClientMockMetricsParamPtrs{}
	}
	mmMetrics.defaultExpectation.paramPtrs.in = &in
	mmMetrics.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmMetrics
}

// ExpectOptsParam3 sets up expected param opts for ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) ExpectOptsParam3(opts ...grpc.CallOption) *mShardClientMockMetrics {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	if mmMetrics.defaultExpectation == nil {
		mmMetrics.defaultExpectation = &ShardClientMockMetricsExpectation{}
	}

	if mmMetrics.defaultExpectation.params != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Expect")
	}

	if mmMetrics.defaultExpectation.paramPtrs == nil {
		mmMetrics.defaultExpectation.paramPtrs = &ShardClientMockMetricsParamPtrs{}
	}
	mmMetrics.defaultExpectation.paramPtrs.opts = &opts
	mmMetrics.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmMetrics
}

// Inspect accepts an inspector function that has same arguments as the ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) Inspect(f func(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption)) *mShardClientMockMetrics {
	if mmMetrics.mock.inspectFuncMetrics != nil {
		mmMetrics.mock.t.Fatalf("Inspect function is already set for ShardClientMock.Metrics")
	}

	mmMetrics.mock.inspectFuncMetrics = f

	return mmMetrics
}

// Return sets up results that will be returned by ShardClient.Metrics
func (mmMetrics *mShardClientMockMetrics) Return(mp1 *mm_pbshard.MetricsResponse, err error) *ShardClientMock {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	if mmMetrics.defaultExpectation == nil {
		mmMetrics.defaultExpectation = &ShardClientMockMetricsExpectation{mock: mmMetrics.mock}
	}
	mmMetrics.defaultExpectation.results = &ShardClientMockMetricsResults{mp1, err}
	mmMetrics.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmMetrics.mock
}

// Set uses given function f to mock the ShardClient.Metrics method
func (mmMetrics *mShardClientMockMetrics) Set(f func(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (mp1 *mm_pbshard.MetricsResponse, err error)) *ShardClientMock {
	if mmMetrics.defaultExpectation != nil {
		mmMetrics.mock.t.Fatalf("Default expectation is already set for the ShardClient.Metrics method")
	}

	if len(mmMetrics.expectations) > 0 {
		mmMetrics.mock.t.Fatalf("Some expectations are already set for the ShardClient.Metrics method")
	}

	mmMetrics.mock.funcMetrics = f
	mmMetrics.mock.funcMetricsOrigin = minimock.CallerInfo(1)
	return mmMetrics.mock
}

// When sets expectation for the ShardClient.Metrics which will trigger the result defined by the following
// Then helper
func (mmMetrics *mShardClientMockMetrics) When(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) *ShardClientMockMetricsExpectation {
	if mmMetrics.mock.funcMetrics != nil {
		mmMetrics.mock.t.Fatalf("ShardClientMock.Metrics mock is already set by Set")
	}

	expectation := &ShardClientMockMetricsExpectation{
		mock:               mmMetrics.mock,
		params:             &ShardClientMockMetricsParams{ctx, in, opts},
		expectationOrigins: ShardClientMockMetricsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmMetrics.expectations = append(mmMetrics.expectations, expectation)
	return expectation
}

// Then sets up ShardClient.Metrics return parameters for the expectation previously defined by the When method
func (e *ShardClientMockMetricsExpectation) Then(mp1 *mm_pbshard.MetricsResponse, err error) *ShardClientMock {
	e.results = &ShardClientMockMetricsResults{mp1, err}
	return e.mock
}

// Times sets number of times ShardClient.Metrics should be invoked
func (mmMetrics *mShardClientMockMetrics) Times(n uint64) *mShardClientMockMetrics {
	if n == 0 {
		mmMetrics.mock.t.Fatalf("Times of ShardClientMock.Metrics mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmMetrics.expectedInvocations, n)
	mmMetrics.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmMetrics
}

func (mmMetrics *mShardClientMockMetrics) invocationsDone() bool {
	if len(mmMetrics.expectations) == 0 && mmMetrics.defaultExpectation == nil && mmMetrics.mock.funcMetrics == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmMetrics.mock.afterMetricsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmMetrics.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Metrics implements mm_pbshard.ShardClient
func (mmMetrics *ShardClientMock) Metrics(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (mp1 *mm_pbshard.MetricsResponse, err error) {
	mm_atomic.AddUint64(&mmMetrics.beforeMetricsCounter, 1)
	defer mm_atomic.AddUint64(&mmMetrics.afterMetricsCounter, 1)

	mmMetrics.t.Helper()

	if mmMetrics.inspectFuncMetrics != nil {
		mmMetrics.inspectFuncMetrics(ctx, in, opts...)
	}

	mm_params := ShardClientMockMetricsParams{ctx, in, opts}

	// Record call args
	mmMetrics.MetricsMock.mutex.Lock()
	mmMetrics.MetricsMock.callArgs = append(mmMetrics.MetricsMock.callArgs, &mm_params)
	mmMetrics.MetricsMock.mutex.Unlock()

	for _, e := range mmMetrics.MetricsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mp1, e.results.err
		}
	}

	if mmMetrics.MetricsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmMetrics.MetricsMock.defaultExpectation.Counter, 1)
		mm_want := mmMetrics.MetricsMock.defaultExpectation.params
		mm_want_ptrs := mmMetrics.MetricsMock.defaultExpectation.paramPtrs

		mm_got := ShardClientMockMetricsParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmMetrics.t.Errorf("ShardClientMock.Metrics got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMetrics.MetricsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmMetrics.t.Errorf("ShardClientMock.Metrics got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMetrics.MetricsMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmMetrics.t.Errorf("ShardClientMock.Metrics got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMetrics.MetricsMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmMetrics.t.Errorf("ShardClientMock.Metrics got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmMetrics.MetricsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmMetrics.MetricsMock.defaultExpectation.results
		if mm_results == nil {
			mmMetrics.t.Fatal("No results are set for the ShardClientMock.Metrics")
		}
		return (*mm_results).mp1, (*mm_results).err
	}
	if mmMetrics.funcMetrics != nil {
		return mmMetrics.funcMetrics(ctx, in, opts...)
	}
	mmMetrics.t.Fatalf("Unexpected call to ShardClientMock.Metrics. %v %v %v", ctx, in, opts)
	return
}

// MetricsAfterCounter returns a count of finished ShardClientMock.Metrics invocations
func (mmMetrics *ShardClientMock) MetricsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMetrics.afterMetricsCounter)
}

// MetricsBeforeCounter returns a count of ShardClientMock.Metrics invocations
func (mmMetrics *ShardClientMock) MetricsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMetrics.beforeMetricsCounter)
}

// Calls returns a list of arguments used in each call to ShardClientMock.Metrics.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmMetrics *mShardClientMockMetrics) Calls() []*ShardClientMockMetricsParams {
	mmMetrics.mutex.RLock()

	argCopy := make([]*ShardClientMockMetricsParams, len(mmMetrics.callArgs))
	copy(argCopy, mmMetrics.callArgs)

	mmMetrics.mutex.RUnlock()

	return argCopy
}

// MinimockMetricsDone returns true if the count of the Metrics invocations corresponds
// the number of defined expectations
func (m *ShardClientMock) MinimockMetricsDone() bool {
	if m.MetricsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.MetricsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.MetricsMock.invocationsDone()
}

// MinimockMetricsInspect logs each unmet expectation
func (m *ShardClientMock) MinimockMetricsInspect() {
	for _, e := range m.MetricsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShardClientMock.Metrics at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterMetricsCounter := mm_atomic.LoadUint64(&m.afterMetricsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.MetricsMock.defaultExpectation != nil && afterMetricsCounter < 1 {
		if m.MetricsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShardClientMock.Metrics at\n%s", m.MetricsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShardClientMock.Metrics at\n%s with params: %#v", m.MetricsMock.defaultExpectation.expectationOrigins.origin, *m.MetricsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcMetrics != nil && afterMetricsCounter < 1 {
		m.t.Errorf("Expected call to ShardClientMock.Metrics at\n%s", m.funcMetricsOrigin)
	}

	if !m.MetricsMock.invocationsDone() && afterMetricsCounter > 0 {
		m.t.Errorf("Expected %d calls to ShardClientMock.Metrics at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.MetricsMock.expectedInvocations), m.MetricsMock.expectedInvocationsOrigin, afterMetricsCounter)
	}
}

type mShardClientMockSet struct {
	optional           bool
	mock               *ShardClientMock
	defaultExpectation *ShardClientMockSetExpectation
	expectations       []*ShardClientMockSetExpectation

	callArgs []*ShardClientMockSetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShardClientMockSetExpectation specifies expectation struct of the ShardClient.Set
type ShardClientMockSetExpectation struct {
	mock               *ShardClientMock
	params             *ShardClientMockSetParams
	paramPtrs          *ShardClientMockSetParamPtrs
	expectationOrigins ShardClientMockSetExpectationOrigins
	results            *ShardClientMockSetResults
	returnOrigin       string
	Counter            uint64
}

// ShardClientMockSetParams contains parameters of the ShardClient.Set
type ShardClientMockSetParams struct {
	ctx  context.Context
	in   *mm_pbshard.SetRequest
	opts []grpc.CallOption
}

// ShardClientMockSetParamPtrs contains pointers to parameters of the ShardClient.Set
type ShardClientMockSetParamPtrs struct {
	ctx  *context.Context
	in   **mm_pbshard.SetRequest
	opts *[]grpc.CallOption
}

// ShardClientMockSetResults contains results of the ShardClient.Set
type ShardClientMockSetResults struct {
	ep1 *empty.Empty
	err error
}

// ShardClientMockSetOrigins contains origins of expectations of the ShardClient.Set
type ShardClientMockSetExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSet *mShardClientMockSet) Optional() *mShardClientMockSet {
	mmSet.optional = true
	return mmSet
}

// Expect sets up expected params for ShardClient.Set
func (mmSet *mShardClientMockSet) Expect(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption) *mShardClientMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &ShardClientMockSetExpectation{}
	}

	if mmSet.defaultExpectation.paramPtrs != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by ExpectParams functions")
	}

	mmSet.defaultExpectation.params = &ShardClientMockSetParams{ctx, in, opts}
	mmSet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSet.expectations {
		if minimock.Equal(e.params, mmSet.defaultExpectation.params) {
			mmSet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSet.defaultExpectation.params)
		}
	}

	return mmSet
}

// ExpectCtxParam1 sets up expected param ctx for ShardClient.Set
func (mmSet *mShardClientMockSet) ExpectCtxParam1(ctx context.Context) *mShardClientMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &ShardClientMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &ShardClientMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.ctx = &ctx
	mmSet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSet
}

// ExpectInParam2 sets up expected param in for ShardClient.Set
func (mmSet *mShardClientMockSet) ExpectInParam2(in *mm_pbshard.SetRequest) *mShardClientMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &ShardClientMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &ShardClientMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.in = &in
	mmSet.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmSet
}

// ExpectOptsParam3 sets up expected param opts for ShardClient.Set
func (mmSet *mShardClientMockSet) ExpectOptsParam3(opts ...grpc.CallOption) *mShardClientMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &ShardClientMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &ShardClientMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.opts = &opts
	mmSet.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmSet
}

// Inspect accepts an inspector function that has same arguments as the ShardClient.Set
func (mmSet *mShardClientMockSet) Inspect(f func(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption)) *mShardClientMockSet {
	if mmSet.mock.inspectFuncSet != nil {
		mmSet.mock.t.Fatalf("Inspect function is already set for ShardClientMock.Set")
	}

	mmSet.mock.inspectFuncSet = f

	return mmSet
}

// Return sets up results that will be returned by ShardClient.Set
func (mmSet *mShardClientMockSet) Return(ep1 *empty.Empty, err error) *ShardClientMock {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &ShardClientMockSetExpectation{mock: mmSet.mock}
	}
	mmSet.defaultExpectation.results = &ShardClientMockSetResults{ep1, err}
	mmSet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSet.mock
}

// Set uses given function f to mock the ShardClient.Set method
func (mmSet *mShardClientMockSet) Set(f func(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption) (ep1 *empty.Empty, err error)) *ShardClientMock {
	if mmSet.defaultExpectation != nil {
		mmSet.mock.t.Fatalf("Default expectation is already set for the ShardClient.Set method")
	}

	if len(mmSet.expectations) > 0 {
		mmSet.mock.t.Fatalf("Some expectations are already set for the ShardClient.Set method")
	}

	mmSet.mock.funcSet = f
	mmSet.mock.funcSetOrigin = minimock.CallerInfo(1)
	return mmSet.mock
}

// When sets expectation for the ShardClient.Set which will trigger the result defined by the following
// Then helper
func (mmSet *mShardClientMockSet) When(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption) *ShardClientMockSetExpectation {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("ShardClientMock.Set mock is already set by Set")
	}

	expectation := &ShardClientMockSetExpectation{
		mock:               mmSet.mock,
		params:             &ShardClientMockSetParams{ctx, in, opts},
		expectationOrigins: ShardClientMockSetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSet.expectations = append(mmSet.expectations, expectation)
	return expectation
}

// Then sets up ShardClient.Set return parameters for the expectation previously defined by the When method
func (e *ShardClientMockSetExpectation) Then(ep1 *empty.Empty, err error) *ShardClientMock {
	e.results = &ShardClientMockSetResults{ep1, err}
	return e.mock
}

// Times sets number of times ShardClient.Set should be invoked
func (mmSet *mShardClientMockSet) Times(n uint64) *mShardClientMockSet {
	if n == 0 {
		mmSet.mock.t.Fatalf("Times of ShardClientMock.Set mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSet.expectedInvocations, n)
	mmSet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSet
}

func (mmSet *mShardClientMockSet) invocationsDone() bool {
	if len(mmSet.expectations) == 0 && mmSet.defaultExpectation == nil && mmSet.mock.funcSet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSet.mock.afterSetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Set implements mm_pbshard.ShardClient
func (mmSet *ShardClientMock) Set(ctx context.Context, in *mm_pbshard.SetRequest, opts ...grpc.CallOption) (ep1 *empty.Empty, err error) {
	mm_atomic.AddUint64(&mmSet.beforeSetCounter, 1)
	defer mm_atomic.AddUint64(&mmSet.afterSetCounter, 1)

	mmSet.t.Helper()

	if mmSet.inspectFuncSet != nil {
		mmSet.inspectFuncSet(ctx, in, opts...)
	}

	mm_params := ShardClientMockSetParams{ctx, in, opts}

	// Record call args
	mmSet.SetMock.mutex.Lock()
	mmSet.SetMock.callArgs = append(mmSet.SetMock.callArgs, &mm_params)
	mmSet.SetMock.mutex.Unlock()

	for _, e := range mmSet.SetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ep1, e.results.err
		}
	}

	if mmSet.SetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSet.SetMock.defaultExpectation.Counter, 1)
		mm_want := mmSet.SetMock.defaultExpectation.params
		mm_want_ptrs := mmSet.SetMock.defaultExpectation.paramPtrs

		mm_got := ShardClientMockSetParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSet.t.Errorf("ShardClientMock.Set got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmSet.t.Errorf("ShardClientMock.Set got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmSet.t.Errorf("ShardClientMock.Set got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSet.t.Errorf("ShardClientMock.Set got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSet.SetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSet.SetMock.defaultExpectation.results
		if mm_results == nil {
			mmSet.t.Fatal("No results are set for the ShardClientMock.Set")
		}
		return (*mm_results).ep1, (*mm_results).err
	}
	if mmSet.funcSet != nil {
		return mmSet.funcSet(ctx, in, opts...)
	}
	mmSet.t.Fatalf("Unexpected call to ShardClientMock.Set. %v %v %v", ctx, in, opts)
	return
}

// SetAfterCounter returns a count of finished ShardClientMock.Set invocations
func (mmSet *ShardClientMock) SetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSet.afterSetCounter)
}

// SetBeforeCounter returns a count of ShardClientMock.Set invocations
func (mmSet *ShardClientMock) SetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSet.beforeSetCounter)
}

// Calls returns a list of arguments used in each call to ShardClientMock.Set.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSet *mShardClientMockSet) Calls() []*ShardClientMockSetParams {
	mmSet.mutex.RLock()

	argCopy := make([]*ShardClientMockSetParams, len(mmSet.callArgs))
	copy(argCopy, mmSet.callArgs)

	mmSet.mutex.RUnlock()

	return argCopy
}

// MinimockSetDone returns true if the count of the Set invocations corresponds
// the number of defined expectations
func (m *ShardClientMock) MinimockSetDone() bool {
	if m.SetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetMock.invocationsDone()
}

// MinimockSetInspect logs each unmet expectation
func (m *ShardClientMock) MinimockSetInspect() {
	for _, e := range m.SetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShardClientMock.Set at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetCounter := mm_atomic.LoadUint64(&m.afterSetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetMock.defaultExpectation != nil && afterSetCounter < 1 {
		if m.SetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShardClientMock.Set at\n%s", m.SetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShardClientMock.Set at\n%s with params: %#v", m.SetMock.defaultExpectation.expectationOrigins.origin, *m.SetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSet != nil && afterSetCounter < 1 {
		m.t.Errorf("Expected call to ShardClientMock.Set at\n%s", m.funcSetOrigin)
	}

	if !m.SetMock.invocationsDone() && afterSetCounter > 0 {
		m.t.Errorf("Expected %d calls to ShardClientMock.Set at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetMock.expectedInvocations), m.SetMock.expectedInvocationsOrigin, afterSetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ShardClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteInspect()

			m.MinimockGetInspect()

			m.MinimockMetricsInspect()

			m.MinimockSetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ShardClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ShardClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteDone() &&
		m.MinimockGetDone() &&
		m.MinimockMetricsDone() &&
		m.MinimockSetDone()
}
