// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: skylr-overseer.proto

package pbovr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Overseer_Register_FullMethodName = "/skylr_overseer.v1.Overseer/Register"
)

// OverseerClient is the client API for Overseer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Overseer - grpc overseer service
type OverseerClient interface {
	// Register registers a new shard in the system
	Register(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type overseerClient struct {
	cc grpc.ClientConnInterface
}

func NewOverseerClient(cc grpc.ClientConnInterface) OverseerClient {
	return &overseerClient{cc}
}

func (c *overseerClient) Register(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Overseer_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverseerServer is the server API for Overseer service.
// All implementations must embed UnimplementedOverseerServer
// for forward compatibility.
//
// Overseer - grpc overseer service
type OverseerServer interface {
	// Register registers a new shard in the system
	Register(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedOverseerServer()
}

// UnimplementedOverseerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOverseerServer struct{}

func (UnimplementedOverseerServer) Register(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedOverseerServer) mustEmbedUnimplementedOverseerServer() {}
func (UnimplementedOverseerServer) testEmbeddedByValue()                  {}

// UnsafeOverseerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OverseerServer will
// result in compilation errors.
type UnsafeOverseerServer interface {
	mustEmbedUnimplementedOverseerServer()
}

func RegisterOverseerServer(s grpc.ServiceRegistrar, srv OverseerServer) {
	// If the following call panics, it indicates UnimplementedOverseerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Overseer_ServiceDesc, srv)
}

func _Overseer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverseerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Overseer_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverseerServer).Register(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Overseer_ServiceDesc is the grpc.ServiceDesc for Overseer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Overseer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skylr_overseer.v1.Overseer",
	HandlerType: (*OverseerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Overseer_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skylr-overseer.proto",
}
