// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: skylr-overseer.proto

package pbovr

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest - register request params
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_skylr_overseer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_overseer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_skylr_overseer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// LookupRequest - lookup request params
type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_skylr_overseer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_overseer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_skylr_overseer_proto_rawDescGZIP(), []int{1}
}

func (x *LookupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// LookupResponse - lookup response
type LookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_address is the gRPC address of the shard responsible for the key
	ShardAddress  string `protobuf:"bytes,1,opt,name=shard_address,json=shardAddress,proto3" json:"shard_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_skylr_overseer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skylr_overseer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_skylr_overseer_proto_rawDescGZIP(), []int{2}
}

func (x *LookupResponse) GetShardAddress() string {
	if x != nil {
		return x.ShardAddress
	}
	return ""
}

var File_skylr_overseer_proto protoreflect.FileDescriptor

const file_skylr_overseer_proto_rawDesc = "" +
	"\n" +
	"\x14skylr-overseer.proto\x12\x11skylr_overseer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"!\n" +
	"\rLookupRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"5\n" +
	"\x0eLookupResponse\x12#\n" +
	"\rshard_address\x18\x01 \x01(\tR\fshardAddress2\xd3\x01\n" +
	"\bOverseer\x12`\n" +
	"\bRegister\x12\".skylr_overseer.v1.RegisterRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/api/v1/register\x12e\n" +
	"\x06Lookup\x12 .skylr_overseer.v1.LookupRequest\x1a!.skylr_overseer.v1.LookupResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/lookupB\x18Z\x16./skylr-overseer;pbovrb\x06proto3"

var (
	file_skylr_overseer_proto_rawDescOnce sync.Once
	file_skylr_overseer_proto_rawDescData []byte
)

func file_skylr_overseer_proto_rawDescGZIP() []byte {
	file_skylr_overseer_proto_rawDescOnce.Do(func() {
		file_skylr_overseer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skylr_overseer_proto_rawDesc), len(file_skylr_overseer_proto_rawDesc)))
	})
	return file_skylr_overseer_proto_rawDescData
}

var file_skylr_overseer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_skylr_overseer_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: skylr_overseer.v1.RegisterRequest
	(*LookupRequest)(nil),   // 1: skylr_overseer.v1.LookupRequest
	(*LookupResponse)(nil),  // 2: skylr_overseer.v1.LookupResponse
	(*empty.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_skylr_overseer_proto_depIdxs = []int32{
	0, // 0: skylr_overseer.v1.Overseer.Register:input_type -> skylr_overseer.v1.RegisterRequest
	1, // 1: skylr_overseer.v1.Overseer.Lookup:input_type -> skylr_overseer.v1.LookupRequest
	3, // 2: skylr_overseer.v1.Overseer.Register:output_type -> google.protobuf.Empty
	2, // 3: skylr_overseer.v1.Overseer.Lookup:output_type -> skylr_overseer.v1.LookupResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skylr_overseer_proto_init() }
func file_skylr_overseer_proto_init() {
	if File_skylr_overseer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skylr_overseer_proto_rawDesc), len(file_skylr_overseer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skylr_overseer_proto_goTypes,
		DependencyIndexes: file_skylr_overseer_proto_depIdxs,
		MessageInfos:      file_skylr_overseer_proto_msgTypes,
	}.Build()
	File_skylr_overseer_proto = out.File
	file_skylr_overseer_proto_goTypes = nil
	file_skylr_overseer_proto_depIdxs = nil
}
